"""
ArmPilot-AI — PDF Report Generator
Generates PDF reports using reportlab. Falls back to raising ImportError
if reportlab is not installed.
"""

from __future__ import annotations

import io
from typing import Any, Optional

from app.core.logger import logger
from app.schemas.benchmark import BenchmarkResult
from app.schemas.optimization import OptimizationResult

try:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch, mm
    from reportlab.platypus import (
        SimpleDocTemplate,
        Table,
        TableStyle,
        Paragraph,
        Spacer,
        HRFlowable,
    )

    HAS_REPORTLAB = True
except ImportError:
    HAS_REPORTLAB = False

try:
    from app.reports.charts import (
        render_latency_chart,
        render_resource_usage_chart,
        render_optimization_comparison_chart,
    )
except ImportError:
    render_latency_chart = None  # type: ignore[assignment]
    render_resource_usage_chart = None  # type: ignore[assignment]
    render_optimization_comparison_chart = None  # type: ignore[assignment]


def generate_benchmark_pdf(
    result: BenchmarkResult,
    *,
    include_charts: bool = True,
    include_hardware: bool = True,
    include_reproduction: bool = True,
) -> bytes:
    """Generate a PDF report for a benchmark run. Returns PDF bytes."""
    if not HAS_REPORTLAB:
        raise ImportError(
            "reportlab is required for PDF generation. "
            "Install it with: pip install reportlab"
        )

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=0.75 * inch, bottomMargin=0.75 * inch)
    styles = getSampleStyleSheet()
    story: list[Any] = []

    # Custom styles
    title_style = ParagraphStyle(
        "ArmPilotTitle", parent=styles["Title"], fontSize=18, spaceAfter=12,
        textColor=colors.HexColor("#1a1d27"),
    )
    heading_style = ParagraphStyle(
        "ArmPilotHeading", parent=styles["Heading2"], fontSize=13,
        spaceAfter=8, textColor=colors.HexColor("#6366f1"),
    )
    body_style = ParagraphStyle(
        "ArmPilotBody", parent=styles["BodyText"], fontSize=9, leading=13,
    )
    mono_style = ParagraphStyle(
        "ArmPilotMono", parent=styles["Code"], fontSize=8, leading=11,
        backColor=colors.HexColor("#f3f4f6"),
    )

    hw = result.hardware or {}
    cfg = result.config

    # Title
    story.append(Paragraph(f"Benchmark Report — {cfg.model}", title_style))
    story.append(Paragraph(f"Generated by ArmPilot-AI", body_style))
    story.append(Spacer(1, 6))
    story.append(HRFlowable(width="100%", color=colors.HexColor("#e5e7eb")))
    story.append(Spacer(1, 12))

    # Metadata
    story.append(Paragraph("Summary", heading_style))
    meta_data = [
        ["Report ID", result.id],
        ["Status", result.status],
        ["Model", cfg.model],
        ["Runtime", cfg.runtime],
        ["Quantization", cfg.quantization or "Default"],
        ["Timestamp", result.timestamp or ""],
    ]
    story.append(_make_table(meta_data, styles))
    story.append(Spacer(1, 12))

    # Hardware
    if include_hardware and hw:
        story.append(Paragraph("Hardware", heading_style))
        hw_data = [
            ["Architecture", hw.get("architecture", "N/A")],
            ["CPU Model", hw.get("cpu_model", "N/A")],
            ["CPU Cores", f"{hw.get('cpu_count', 'N/A')} (physical: {hw.get('cpu_count_physical', 'N/A')})"],
            ["Memory", f"{hw.get('memory_total_gb', 'N/A')} GB"],
            ["ARM64", "Yes" if hw.get("is_arm64") else "No"],
            ["Platform", hw.get("platform", "N/A")],
        ]
        story.append(_make_table(hw_data, styles))
        story.append(Spacer(1, 12))

    # Configuration
    story.append(Paragraph("Configuration", heading_style))
    cfg_data = [
        ["Batch Size", str(cfg.batch_size)],
        ["Threads", str(cfg.threads)],
        ["Concurrency", str(cfg.concurrency)],
        ["Num Requests", str(cfg.num_requests)],
        ["Max Tokens", str(cfg.max_tokens)],
    ]
    story.append(_make_table(cfg_data, styles))
    story.append(Spacer(1, 12))

    # Results
    story.append(Paragraph("Results", heading_style))
    results_data = [
        ["Metric", "Value"],
        ["TTFT", _fmt(result.ttft_ms, "ms")],
        ["Tokens/sec", _fmt(result.tokens_per_second)],
        ["Requests/sec", _fmt(result.requests_per_second)],
        ["Total Tokens", str(result.total_tokens)],
        ["Total Requests", str(result.total_requests)],
        ["Duration", _fmt(result.duration_seconds, "s")],
    ]
    story.append(_make_table(results_data, styles))
    story.append(Spacer(1, 12))

    # Latency
    story.append(Paragraph("Latency Distribution", heading_style))
    lat = result.latency
    lat_data = [
        ["Percentile", "Value (ms)"],
        ["P50", _fmt(lat.p50_ms, "ms")],
        ["P75", _fmt(lat.p75_ms, "ms")],
        ["P90", _fmt(lat.p90_ms, "ms")],
        ["P95", _fmt(lat.p95_ms, "ms")],
        ["P99", _fmt(lat.p99_ms, "ms")],
        ["Avg", _fmt(lat.avg_ms, "ms")],
        ["Min", _fmt(lat.min_ms, "ms")],
        ["Max", _fmt(lat.max_ms, "ms")],
    ]
    story.append(_make_table(lat_data, styles))
    story.append(Spacer(1, 12))

    # Resource Usage
    story.append(Paragraph("Resource Usage", heading_style))
    res_data = [
        ["Resource", "Value"],
        ["CPU Utilization", _fmt(result.cpu_utilization_percent, "%")],
        ["Memory (RSS)", _fmt(result.memory_mb, "MB")],
        ["Memory Peak", _fmt(result.memory_peak_mb, "MB")],
        ["Model Size", _fmt(result.model_size_mb, "MB")],
    ]
    story.append(_make_table(res_data, styles))
    story.append(Spacer(1, 12))

    # Reproduction
    if include_reproduction:
        story.append(Paragraph("Reproduction", heading_style))
        cmd = (
            f"arm-infer benchmark \\\n"
            f"  --model {cfg.model} \\\n"
            f"  --runtime {cfg.runtime} \\\n"
            f"  --batch-size {cfg.batch_size} \\\n"
            f"  --threads {cfg.threads} \\\n"
            f"  --concurrency {cfg.concurrency} \\\n"
            f"  --num-requests {cfg.num_requests} \\\n"
            f"  --max-tokens {cfg.max_tokens}"
        )
        story.append(Paragraph(cmd.replace("\n", "<br/>"), mono_style))

    doc.build(story)
    return buf.getvalue()


def generate_optimization_pdf(
    result: OptimizationResult,
    *,
    include_charts: bool = True,
    include_reproduction: bool = True,
) -> bytes:
    """Generate a PDF report for an optimization run. Returns PDF bytes."""
    if not HAS_REPORTLAB:
        raise ImportError(
            "reportlab is required for PDF generation. "
            "Install it with: pip install reportlab"
        )

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=0.75 * inch, bottomMargin=0.75 * inch)
    styles = getSampleStyleSheet()
    story: list[Any] = []

    title_style = ParagraphStyle(
        "ArmPilotTitle", parent=styles["Title"], fontSize=18, spaceAfter=12,
        textColor=colors.HexColor("#1a1d27"),
    )
    heading_style = ParagraphStyle(
        "ArmPilotHeading", parent=styles["Heading2"], fontSize=13,
        spaceAfter=8, textColor=colors.HexColor("#6366f1"),
    )
    body_style = ParagraphStyle(
        "ArmPilotBody", parent=styles["BodyText"], fontSize=9, leading=13,
    )

    story.append(Paragraph(f"Optimization Report — {result.config.model}", title_style))
    story.append(Paragraph("Generated by ArmPilot-AI", body_style))
    story.append(Spacer(1, 6))
    story.append(HRFlowable(width="100%", color=colors.HexColor("#e5e7eb")))
    story.append(Spacer(1, 12))

    # Summary
    story.append(Paragraph("Summary", heading_style))
    meta_data = [
        ["Report ID", result.id],
        ["Status", result.status],
        ["Model", result.config.model],
        ["Objective", result.config.objective],
        ["Timestamp", result.timestamp or ""],
    ]
    story.append(_make_table(meta_data, styles))
    story.append(Spacer(1, 12))

    # Baseline
    if result.baseline:
        story.append(Paragraph("Baseline", heading_style))
        baseline_rows = [["Metric", "Value"]]
        for k, v in result.baseline.items():
            if k != "benchmark_id":
                baseline_rows.append([k, str(v)])
        story.append(_make_table(baseline_rows, styles))
        story.append(Spacer(1, 12))

    # Best candidate
    if result.best_candidate:
        story.append(Paragraph("Best Configuration", heading_style))
        bc = result.best_candidate
        bc_data = [
            ["Name", bc.name],
            ["Tokens/sec", _fmt(bc.tokens_per_second)],
            ["TTFT", _fmt(bc.ttft_ms, "ms")],
            ["P95 Latency", _fmt(bc.p95_latency_ms, "ms")],
            ["Memory", _fmt(bc.memory_mb, "MB")],
        ]
        story.append(_make_table(bc_data, styles))
        story.append(Spacer(1, 12))

    # Improvements
    if result.improvement_summary:
        story.append(Paragraph("Improvements", heading_style))
        imp_rows = [["Metric", "Before", "After", "Change"]]
        for metric, data in result.improvement_summary.items():
            if isinstance(data, dict):
                imp_rows.append([
                    metric,
                    str(data.get("before", "")),
                    str(data.get("after", "")),
                    f"{data.get('change_percent', 0):+.1f}%",
                ])
        story.append(_make_table(imp_rows, styles))
        story.append(Spacer(1, 12))

    # Candidates
    if result.candidates:
        story.append(Paragraph("All Candidates", heading_style))
        cand_rows = [["Name", "Tokens/sec", "TTFT", "P95", "Memory", "Status"]]
        for c in result.candidates:
            cand_rows.append([
                c.name,
                _fmt(c.tokens_per_second),
                _fmt(c.ttft_ms, "ms"),
                _fmt(c.p95_latency_ms, "ms"),
                _fmt(c.memory_mb, "MB"),
                c.status,
            ])
        story.append(_make_table(cand_rows, styles))

    doc.build(story)
    return buf.getvalue()


# ── Helpers ──────────────────────────────────────────────────────────────

def _make_table(data: list[list[str]], styles: Any) -> Table:
    """Create a styled reportlab Table from a 2D list."""
    t = Table(data, repeatRows=1 if len(data) > 1 else 0)
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f3f4f6")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.HexColor("#374151")),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("LEADING", (0, 0), (-1, -1), 13),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 6),
        ("TOPPADDING", (0, 0), (-1, 0), 6),
        ("BOTTOMPADDING", (0, 1), (-1, -1), 4),
        ("TOPPADDING", (0, 1), (-1, -1), 4),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e5e7eb")),
        ("ALIGN", (1, 0), (-1, -1), "LEFT"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
    ]))
    return t


def _fmt(value: Any, unit: str = "") -> str:
    if value is None:
        return "N/A"
    if isinstance(value, float):
        return f"{value:.1f} {unit}".strip()
    return f"{value} {unit}".strip()
