"""
ArmPilot-AI — Markdown Report Builder
Generates reproducible benchmark/optimization reports.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Any, Optional

from app.schemas.benchmark import BenchmarkResult
from app.schemas.optimization import OptimizationResult


def generate_benchmark_report(result: BenchmarkResult) -> str:
    """Generate a Markdown report for a benchmark run."""
    hw = result.hardware or {}
    cfg = result.config
    ts = result.timestamp or datetime.now(timezone.utc).isoformat()

    lines: list[str] = [
        "# ArmPilot-AI — Benchmark Report",
        "",
        f"**Report ID:** {result.id}",
        f"**Timestamp:** {ts}",
        f"**Status:** {result.status}",
        "",
        "---",
        "",
        "## Hardware",
        "",
        f"| Field | Value |",
        f"|-------|-------|",
        f"| Architecture | {hw.get('architecture', 'N/A')} |",
        f"| CPU Model | {hw.get('cpu_model', 'N/A')} |",
        f"| CPU Cores | {hw.get('cpu_count', 'N/A')} (physical: {hw.get('cpu_count_physical', 'N/A')}) |",
        f"| Memory | {hw.get('memory_total_gb', 'N/A')} GB |",
        f"| ARM64 | {'Yes' if hw.get('is_arm64') else 'No'} |",
        f"| Platform | {hw.get('platform', 'N/A')} |",
        "",
        "## Configuration",
        "",
        f"| Parameter | Value |",
        f"|-----------|-------|",
        f"| Model | {cfg.model} |",
        f"| Runtime | {cfg.runtime} |",
        f"| Quantization | {cfg.quantization or 'Default'} |",
        f"| Batch Size | {cfg.batch_size} |",
        f"| Threads | {cfg.threads} |",
        f"| Concurrency | {cfg.concurrency} |",
        f"| Num Requests | {cfg.num_requests} |",
        f"| Max Tokens | {cfg.max_tokens} |",
        "",
        "## Results",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| TTFT | {_fmt(result.ttft_ms, 'ms')} |",
        f"| Tokens/sec | {_fmt(result.tokens_per_second)} |",
        f"| Requests/sec | {_fmt(result.requests_per_second)} |",
        f"| Total Tokens | {result.total_tokens} |",
        f"| Total Requests | {result.total_requests} |",
        f"| Duration | {_fmt(result.duration_seconds, 's')} |",
        "",
        "## Latency",
        "",
        f"| Percentile | Value |",
        f"|------------|-------|",
        f"| P50 | {_fmt(result.latency.p50_ms, 'ms')} |",
        f"| P75 | {_fmt(result.latency.p75_ms, 'ms')} |",
        f"| P90 | {_fmt(result.latency.p90_ms, 'ms')} |",
        f"| P95 | {_fmt(result.latency.p95_ms, 'ms')} |",
        f"| P99 | {_fmt(result.latency.p99_ms, 'ms')} |",
        f"| Avg | {_fmt(result.latency.avg_ms, 'ms')} |",
        f"| Min | {_fmt(result.latency.min_ms, 'ms')} |",
        f"| Max | {_fmt(result.latency.max_ms, 'ms')} |",
        "",
        "## Resource Usage",
        "",
        f"| Resource | Value |",
        f"|----------|-------|",
        f"| CPU Utilization | {_fmt(result.cpu_utilization_percent, '%')} |",
        f"| Memory (RSS) | {_fmt(result.memory_mb, 'MB')} |",
        f"| Model Size | {_fmt(result.model_size_mb, 'MB')} |",
        "",
        "## Reproduction",
        "",
        "```bash",
        f"arm-infer benchmark \\",
        f"  --model {cfg.model} \\",
        f"  --runtime {cfg.runtime} \\",
        f"  --batch-size {cfg.batch_size} \\",
        f"  --threads {cfg.threads} \\",
        f"  --concurrency {cfg.concurrency} \\",
        f"  --num-requests {cfg.num_requests} \\",
        f"  --max-tokens {cfg.max_tokens}",
        "```",
        "",
        "---",
        f"*Generated by ArmPilot-AI at {ts}*",
    ]

    return "\n".join(lines)


def generate_optimization_report(result: OptimizationResult) -> str:
    """Generate a Markdown report for an optimization run."""
    ts = result.timestamp or datetime.now(timezone.utc).isoformat()

    lines: list[str] = [
        "# ArmPilot-AI — Optimization Report",
        "",
        f"**Report ID:** {result.id}",
        f"**Timestamp:** {ts}",
        f"**Model:** {result.config.model}",
        f"**Objective:** {result.config.objective}",
        f"**Status:** {result.status}",
        "",
        "---",
        "",
    ]

    # Baseline
    if result.baseline:
        lines.extend([
            "## Baseline",
            "",
            f"| Metric | Value |",
            f"|--------|-------|",
        ])
        for key, val in result.baseline.items():
            if key != "benchmark_id":
                lines.append(f"| {key} | {val} |")
        lines.append("")

    # Best candidate
    if result.best_candidate:
        bc = result.best_candidate
        lines.extend([
            "## Best Configuration",
            "",
            f"**{bc.name}**",
            "",
            f"| Metric | Value |",
            f"|--------|-------|",
            f"| Tokens/sec | {_fmt(bc.tokens_per_second)} |",
            f"| TTFT | {_fmt(bc.ttft_ms, 'ms')} |",
            f"| P95 Latency | {_fmt(bc.p95_latency_ms, 'ms')} |",
            f"| Memory | {_fmt(bc.memory_mb, 'MB')} |",
            "",
        ])

    # Improvements
    if result.improvement_summary:
        lines.extend(["## Improvements", ""])
        lines.extend([
            f"| Metric | Before | After | Change |",
            f"|--------|--------|-------|--------|",
        ])
        for metric, data in result.improvement_summary.items():
            if isinstance(data, dict):
                lines.append(
                    f"| {metric} | {data.get('before', 'N/A')} | "
                    f"{data.get('after', 'N/A')} | {data.get('change_percent', 0):+.1f}% |"
                )
        lines.append("")

    # All candidates
    if result.candidates:
        lines.extend([
            "## All Candidates",
            "",
            "| Name | TPS | TTFT | P95 | Memory | Status |",
            "|------|-----|------|-----|--------|--------|",
        ])
        for c in result.candidates:
            lines.append(
                f"| {c.name} | {_fmt(c.tokens_per_second)} | "
                f"{_fmt(c.ttft_ms, 'ms')} | {_fmt(c.p95_latency_ms, 'ms')} | "
                f"{_fmt(c.memory_mb, 'MB')} | {c.status} |"
            )
        lines.append("")

    lines.extend([
        "---",
        f"*Generated by ArmPilot-AI at {ts}*",
    ])

    return "\n".join(lines)


def _fmt(value: Any, unit: str = "") -> str:
    """Format a value for display, handling None."""
    if value is None:
        return "N/A"
    if isinstance(value, float):
        return f"{value:.1f} {unit}".strip()
    return f"{value} {unit}".strip()
